### ISSUE TITLE
Add Version struct

### ISSUE THREAD

**Issue by zummenix** [thebreadcat/version#2]
I would like to add something like:

``` rust
pub fn current() -> Version
```

We can implement `Display` trait on `Version` struct.
On call site it would be:

``` rust
println!("Version {}", version::current());
```

**Comment by nulldatamap** [comment]
Done!
Added in 71bdedd.

**Comment by zummenix** [comment]
@nulldatamap Could you please publish the new version on crates.io?

**Comment by nulldatamap** [comment]
I renamed my account since I published the crate. Crates.io does currently not handle account renaming well. The crate's ownership and API key is bound to the prerenaming account, so I can't publish the newest version since I don't have the old API key. I commented on the relevant issue: https://github.com/rust-lang/crates.io/issues/136

**Comment by nulldatamap** [comment]
@zummenix We fixed the crate problem and the newest version of `version` should be on crates.io now!

**Comment by zummenix** [comment]
Cool! Thanks!
